server {
    listen 80;
    server_name baocaochiendich.site;

    # Frontend
    location / {
        proxy_pass http://camp-report-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend API
    location /api/ {
        proxy_pass http://camp-report-backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}